<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Carts\Commands\" />
    <Folder Include="Features\Carts\Queries\" />
    <Folder Include="Features\WishList\Commands\" />
    <Folder Include="Features\WishList\Queries\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.1.0" />
    <PackageReference Include="FluentValidation" Version="12.1.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.0" />
    <PackageReference Include="MediatR" Version="13.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShoppingApp.Domain\ShoppingApp.Domain.csproj" />
  </ItemGroup>

</Project>
